Update configure script for R 4.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Anticonf script by Jeroen Ooms (2015)
+# Anticonf script by Jeroen Ooms (2020)
 # The script will try 'pkg-config' to find required cflags and ldflags.
 # Make sure this executable is in PATH when installing the package.
 # Alternatively, you can set INCLUDE_DIR and LIB_DIR manually:
@@ -11,8 +11,8 @@ PKG_DEB_NAME="libcairo2-dev"
 PKG_RPM_NAME="cairo-devel"
 PKG_CSW_NAME="libcairo_dev"
 PKG_BREW_NAME="cairo"
-PKG_TEST_HEADER="<cairo.h>"
 PKG_LIBS="-lcairo -lfreetype"
+PKG_TEST_FILE="src/tests/sysdeps.c"
 
 # Use pkg-config if available
 if [ $(command -v pkg-config) ]; then
@@ -26,8 +26,8 @@ if [ $(command -v pkg-config) ]; then
   fi
 fi
 
-# Hack because OSX CRAN server has old libcairo
-if [ -e "/Builds/CRAN-QA-Simon" ]; then
+# Hack: we really want our own cairo, not the CRAN one (which depends on XQuartz)
+if [ -e "/Builds/CRAN-QA-Simon" ] || [ -e "/Volumes/Builds" ]; then
   unset PKGCONFIG_CFLAGS
   unset PKGCONFIG_LIBS
 fi
@@ -44,7 +44,7 @@ elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
 elif [[ "$OSTYPE" == "darwin"* ]]; then
   if [ $(command -v brew) ]; then
     BREWDIR=$(brew --prefix)
-    PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include/cairo"
+    PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include/cairo -I/usr/local/opt/freetype/include/freetype2"
     PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
   else
     curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
@@ -62,12 +62,10 @@ echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Test configuration
-echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
-
-# Customize the error
-if [ $R_CONFIG_ERROR ]; then
-  echo "------------------------- ANTICONF ERROR ---------------------------"
-  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E ${PKG_TEST_FILE} >/dev/null 2>configure.log
+if [ $? -ne 0 ]; then
+  echo "-----------------------------[ ANTICONF ]-------------------------------"
+  echo "Configuration failed to find Cairo or Freetype2. Try installing:"
   echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu)"
   echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
   echo " * csw: $PKG_CSW_NAME (Solaris)"
@@ -76,8 +74,10 @@ if [ $R_CONFIG_ERROR ]; then
   echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
   echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
   echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-  echo "--------------------------------------------------------------------"
-  exit 1;
+  echo "---------------------------[ ERROR MESSAGE ]----------------------------"
+  cat configure.log
+  echo "------------------------------------------------------------------------"
+  exit 1
 fi
 
 # Write to Makevars
